#encoding: utf-8
import os

DEBUG = True
#SECRET_KEY = os.urandom(24)
SECRET_KEY = "FSADGQFGVEIOFVNERIONVOEI"
DB_USERNAME = 'root'
DB_PASSWORD = 'root'
DB_HOST = '127.0.0.1'
DB_PORT = '3306'
DB_NAME = 'bbs'
"""
设置session过期时间
PERMANENT_SESSION_LIFETIME = 10(秒)
"""
DB_URI = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (DB_USERNAME,DB_PASSWORD,DB_HOST,DB_PORT,DB_NAME)

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False

CMS_USER_ID = "abcacb"
FRONT_USER_ID = "dfsafdsafdsaf"

#邮箱配置
MAIL_SERVER = "smtp.163.com"
MAIL_PORT = '25'
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_USERNAME = "18860057945@163.com"
MAIL_PASSWORD = "qwertyuiop1234"
MAIL_DEFAULT_SENDER = "18860057945@163.com"

# 阿里大于相关配置
ALIDAYU_APP_KEY = '23709557'
ALIDAYU_APP_SECRET = 'd9e430e0a96e21c92adacb522a905c4b'
ALIDAYU_SIGN_NAME = '小饭桌应用'
ALIDAYU_TEMPLATE_CODE = 'SMS_68465012'

#qiniu
UEDITOR_UPLOAD_TO_QINIU = True
UEDITOR_QINIU_ACCESS_KEY = "ysrNF8IDwKfsATrLxMDbRLbl3AOxu1Qzk3SSA42E"
UEDITOR_QINIU_SECRET_KEY = "g3T4G66brMWUY8fP3AXlIl_WZ3yep-VkUaPAgc-K"
UEDITOR_QINIU_BUCKET_NAME = "flask-study"
UEDITOR_QINIU_DOMAIN = 'http://file.smilehacker.net/'

#flask-paginate的相关配置
PER_PAGE = 10

#flask celery相关配置

CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"