"""empty message

Revision ID: bc977af9f458
Revises: d6f35c68e00c
Create Date: 2018-04-07 18:49:59.716401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc977af9f458'
down_revision = 'd6f35c68e00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', sa.String(length=100), nullable=False))
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=False))
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###
