"""empty message

Revision ID: d6f35c68e00c
Revises: b3b8f7f4e0d7
Create Date: 2018-04-07 18:33:25.014901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6f35c68e00c'
down_revision = 'b3b8f7f4e0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', sa.String(length=100), nullable=False))
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=False))
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###
